'''
write a python program to create a student class and declare the properties as student name, 
student id, branch, percentage, age, paasing out year, certificate count,
create 10 objects and initialize the values using mutator method and access them using accessor method
(Note: You have to intialize the values without using constructors)
'''
class Student():
    def Set_name(self):
        name = input("enter the name of the student: ")
        self.Name = name
    def Set_student_ID(self):
        sd_ID = input("enter the student ID: ")
        self.Sd_ID = sd_ID
    def Set_student_branch(self):
        branch = input("enter student branch: ")
        self.Branch = branch
    def Set_student_percentage(self):
        percentage = input("enter students percentage: ")
        self.Percentage = percentage
    def Set_student_age(self):
        age = input("enter students age: ")
        self.Age = age 
    def Set_student_year(self):
        year = input("enter student year of passing: ")
        self.Year = year
    def Set_student_certifications(self):
        certification = input("enter number of certifications students had: ")
        self.Certifications = certification
    
    def Get_name(self):
        print(f"Student name is: {self.Name}")
    def Get_student_ID(self):
        print(f"Student ID is: {self.Sd_ID}")
    def Get_student_branch(self):
        print(f"Branch of the student is: {self.Branch}")
    def Get_student_percentage(self):
        print(f"Percentage of the student is: {self.Percentage}")
    def Get_student_age(self):
        print(f"age of the student is {self.Age}")
    def Get_student_year(self):
        print(f"Student will be passed in the year of {self.Year}")
    def Get_student_certifications(self):
        print(f"There are {self.Certifications} certificates for the student")

S1 = Student()
S1.Set_name()
S1.Set_student_ID()
S1.Set_student_branch()
S1.Set_student_percentage()
S1.Set_student_age()
S1.Set_student_year()
S1.Set_student_certifications()
print("")

S1.Get_name()
S1.Get_student_ID()
S1.Get_student_branch()
S1.Get_student_percentage()
S1.Get_student_age()
S1.Get_student_year()
S1.Get_student_certifications()
print("*****************************************")

S2 = Student()
S2.Set_name()
S2.Set_student_ID()
S2.Set_student_branch()
S2.Set_student_percentage()
S2.Set_student_age()
S2.Set_student_year()
S2.Set_student_certifications()
print("")

S2.Get_name()
S2.Get_student_ID()
S2.Get_student_branch()
S2.Get_student_percentage()
S2.Get_student_age()
S2.Get_student_year()
S2.Get_student_certifications()
print("*****************************************")
S3 = Student()
S3.Set_name()
S3.Set_student_ID()
S3.Set_student_branch()
S3.Set_student_percentage()
S3.Set_student_age()
S3.Set_student_year()
S3.Set_student_certifications()
print("")

S3.Get_name()
S3.Get_student_ID()
S3.Get_student_branch()
S3.Get_student_percentage()
S3.Get_student_age()
S3.Get_student_year()
S3.Get_student_certifications()
print("*****************************************")
S4 = Student()
S4.Set_name()
S4.Set_student_ID()
S4.Set_student_branch()
S4.Set_student_percentage()
S4.Set_student_age()
S4.Set_student_year()
S4.Set_student_certifications()
print("")

S4.Get_name()
S4.Get_student_ID()
S4.Get_student_branch()
S4.Get_student_percentage()
S4.Get_student_age()
S4.Get_student_year()
S4.Get_student_certifications()
print("*****************************************")
S5 = Student()
S5.Set_name()
S5.Set_student_ID()
S5.Set_student_branch()
S5.Set_student_percentage()
S5.Set_student_age()
S5.Set_student_year()
S5.Set_student_certifications()
print("")

S5.Get_name()
S5.Get_student_ID()
S5.Get_student_branch()
S5.Get_student_percentage()
S5.Get_student_age()
S5.Get_student_year()
S5.Get_student_certifications()
print("*****************************************")
S6 = Student()
S6.Set_name()
S6.Set_student_ID()
S6.Set_student_branch()
S6.Set_student_percentage()
S6.Set_student_age()
S6.Set_student_year()
S6.Set_student_certifications()
print("")


S6.Get_name()
S6.Get_student_ID()
S6.Get_student_branch()
S6.Get_student_percentage()
S6.Get_student_age()
S6.Get_student_year()
S6.Get_student_certifications()
print("*****************************************")
S7 = Student()
S7.Set_name()
S7.Set_student_ID()
S7.Set_student_branch()
S7.Set_student_percentage()
S7.Set_student_age()
S7.Set_student_year()
S7.Set_student_certifications()
print("")

S7.Get_name()
S7.Get_student_ID()
S7.Get_student_branch()
S7.Get_student_percentage()
S7.Get_student_age()
S7.Get_student_year()
S7.Get_student_certifications()
print("*****************************************")
S8 = Student()
S8.Set_name()
S8.Set_student_ID()
S8.Set_student_branch()
S8.Set_student_percentage()
S8.Set_student_age()
S8.Set_student_year()
S8.Set_student_certifications()
print("")

S8.Get_name()
S8.Get_student_ID()
S8.Get_student_branch()
S8.Get_student_percentage()
S8.Get_student_age()
S8.Get_student_year()
S8.Get_student_certifications()
print("*****************************************")
S9 = Student()
S9.Set_name()
S9.Set_student_ID()
S9.Set_student_branch()
S9.Set_student_percentage()
S9.Set_student_age()
S9.Set_student_year()
S9.Set_student_certifications()
print("")

S9.Get_name()
S9.Get_student_ID()
S9.Get_student_branch()
S9.Get_student_percentage()
S9.Get_student_age()
S9.Get_student_year()
S9.Get_student_certifications()
print("*****************************************")
S10 = Student()
S10.Set_name()
S10.Set_student_ID()
S10.Set_student_branch()
S10.Set_student_percentage()
S10.Set_student_age()
S10.Set_student_year()
S10.Set_student_certifications()
print("")

S10.Get_name()
S10.Get_student_ID()
S10.Get_student_branch()
S10.Get_student_percentage()
S10.Get_student_age()
S10.Get_student_year()
S10.Get_student_certifications()
print("*****************************************")