seq=("Enter the sequence : ")
reverse=seq.upper()
complement=seq.upper()
complement.replace('A','T')
complement.replace('G','C')
complement.replace('C','G')
complement.replace('T','A')
print(complement)